const ERROR_CODES = Object.freeze({
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  BUSINESS_RULE_FAILED: 'BUSINESS_RULE_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DOWNSTREAM_SERVICE_ERROR: 'DOWNSTREAM_SERVICE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  CORS_FORBIDDEN: 'CORS_FORBIDDEN',
  
  // HME Project Specific Business Rules
  COMPANY_ADMIN_LIMIT_REACHED: 'COMPANY_ADMIN_LIMIT_REACHED',
  STAFF_LIMIT_REACHED: 'STAFF_LIMIT_REACHED',
  DEMO_ALREADY_USED: 'DEMO_ALREADY_USED',
  SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_LIMIT_REACHED',
});

module.exports = {
  ERROR_CODES,
};
